---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: luluapp
  name: luludeployment
spec:
  selector:
    matchLabels:
      app: luluapp
  template:
    metadata:
      labels:
        app: luluapp
    spec:
      containers:
      - image: luluimage
        name: lulupod
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: luluapp
  name: luluservice
spec:
  ports:
  - nodePort: 32223
    targetPort: 3000
  selector:
    app: luluapp
  type: LoadBalancer
